### ISSUE TITLE
Update generator documentation to show non-deprecated examples

### ISSUE THREAD

**Issue by log4b** [conduitframework/conduit#11]
Hello,

[Supervisor.Spec](https://hexdocs.pm/elixir/Supervisor.Spec.html) was deprecated in Elixir v1.5.

Would be cool to update the docs to suggest the new behavior.

There is two ways to add the broker into our application supervision tree:

- Map based specification
- Module based supervisors

The following code shows the difference:

Current way (deprecated)

```
Also, add your broker to the supervision hierarchy in your example.ex:

    def start(_type, _args) do
      children = [
        # ...
        supervisor(Example.Broker, [])
      ]

      supervise(children, strategy: :one_for_one)
    end
```

New way (Map based specification)

```
Also, add your broker to the supervision hierarchy in your example.ex:

    def start(_type, _args) do
      children = [
        # ...
	    %{
	      id: Example.Broker,
	      start: {Example.Broker, :start_link, []}
	    }
      ]

      supervise(children, strategy: :one_for_one)
    end
```

**Comment by blatyo** [comment]
Thanks, I'd love a contribution if you're interested. The broker implements child_spec, so the example should be simpler.

``` elixir
children = [
  {Example.Broker, []}
]

Supervisor.init(children, strategy: :one_for_one)
```

**Comment by log4b** [comment]
I'd like to make this change.

I'm not aware if you want to support older Elixir versions so I thought on generate the example showing both specs.

Something like this:

```
Also, add your broker to the supervision hierarchy in your conduit.ex:


Elixir v1.4 or below:

    def start(_type, _args) do
      children = [
        # ...
        supervisor(ConduitQueue.Broker, [])
      ]

      supervise(children, strategy: :one_for_one)
    end


Elixir v1.5 or above:

    def start(_type, _args) do
      children = [
        # ...
        {ConduitQueue.Broker, []}
      ]

      supervise(children, strategy: :one_for_one)
    end
```

I'm going to open two PR's, one showing newest example and one containing both, ok?

**Comment by blatyo** [comment]
Let's go with both for now

**Comment by blatyo** [comment]
But put the newer one first
