### ISSUE TITLE
Help w/ deprecation warning?

### ISSUE THREAD

**Issue by coladarci** [conduitframework/conduit#20]
Hello! We just updated from 0.12.5 to 0.12.8 and started seeing this:

```
03:36:45.524 [warn] Calling ApiQueue.Broker.publish/3 with message as second argument is deprecated to enable pipeline usage.

Replace:

    ApiQueue.Broker.publish(:error, message, opts)

With:

    ApiQueue.Broker.publish(message, :error, opts)
```

We don't actually publish, so I'm thinking this might have to do w/ `Conduit.Plug.DeadLetter`? 

Any pointers to get on top of this?

**Comment by blatyo** [comment]
Hey, sorry about that. Mind submitting a PR to change the order of args here: https://github.com/conduitframework/conduit/blob/master/lib/conduit/plug/dead_letter.ex#L57

**Comment by coladarci** [comment]
@blatyo thanks for the quick response - I threw up a pull, not really understanding the full implications, and see the tests are failing. Happy to dig in more when I have some time, but perhaps you have some quick thoughts.

**Comment by blatyo** [comment]
Try out v0.12.9

**Comment by coladarci** [comment]
Thanks - can confirm dead letter still works and there are no warnings.
