### ISSUE TITLE
How do I publish messages?

### ISSUE THREAD

**Issue by timwis** [conduitframework/conduit#26]
Forgive the basic question, but I've poured over the docs for Conduit and ConduitAMQP and I can't seem to find a usage example. The generator was able to get me far enough that I know how to consume a message (I've tested this by manually publishing a message via the rabbitmq dashboard). But how do I publish a message? I see the `outgoing` macro in the DSL, but I can't execute `Broker.outgoing()` or `Broker.publish()`.

**Comment by blatyo** [comment]
Fair question. This should be documented as callbacks on the Broker module.

The slide deck in the README, does an overview of most of the parts.
http://slides.com/blatyo/deck-12#/

There's also an example on the example app README.
https://github.com/conduitframework/conduit_amqp_example

Anyways, the gist is, you do:

``` elixir
Broker.publish(message, :name_of_publish_route_in_broker)
# or
Broker.publish(message, :name_of_publish_route_in_broker, [options: :for_publish])
```

If you don't mind, could you post future questions like this to the elixirforum.com with the tag `conduit` in the Questions/Help section?

Thanks
