### ISSUE TITLE
Support for multiple subscribers to the same message

### ISSUE THREAD

**Issue by nicholasjhenry** [conduitframework/conduit#3]
Am I correct in understanding that Conduit does not support multiple subscribers to the same message?

**Comment by blatyo** [comment]
It depends on the backing message queue. RabbitMQ supports topic exchanges, where you can have multiple queues bound to that exchange. SQS doesn't have anything like that, so you'd have to build something in the application layer to support it. 

If you're just looking for concurrency in the same recipient application, then `Task` and `Task.Supervised` are probably what you want. If you need the same message to go to multiple applications in queues, then you'll have to implement some form of the [recipient list pattern](http://www.enterpriseintegrationpatterns.com/patterns/messaging/RecipientList.html). The easiest place to do that is the sender.

**Comment by blatyo** [comment]
BTW, feel free to ask any follow up questions.

**Comment by nicholasjhenry** [comment]
Thank you for the quick reply on Sunday. I was looking for PubSub implementation for SQS. I currently have a one implemented but I prefer the design of your library. As you mentioned above SQS doesn't support that out of the box and switching over to RabbitMQ seems like a better direction. Thank you again for your help.

**Comment by blatyo** [comment]
Out of curiosity, how were you doing PubSub with SQS and multiple subscribers?

If you go the RabbitMQ route, take a look at the example at the end of [this README](https://github.com/conduitframework/phoenix_pubsub_conduit_amqp#broker). It describes how to use the library as the mechanism for Phoenix PubSub, but you could also not use Phoenix PubSub and the pattern would be similar.

**Comment by nicholasjhenry** [comment]
> Out of curiosity, how were you doing PubSub with SQS and multiple subscribers?

We used GenStage for that, a produce (publisher) pulling messages off SQS and dispatching using `GenStage.BroadcastDispatcher` to the consumers (subscribers).

Thanks for the pointer to the README. I totally missed that Repo somehow :-) Lots of great stuff here, thank you.
