### ISSUE TITLE
nice error when publishing to non-existent atom

### ISSUE THREAD

**Issue by mgk** [conduitframework/conduit#4]
When you publish to something not declared in `broker.ex`, like: 

```elixir
Broker.publish(:foo, ...)
```
you get a stack trace like:

```shell
     ** (MatchError) no match of right hand side value: nil
     code: MyService.call(payload)
     stacktrace:
       (my_app) web/broker.ex:1: MiddleOut.Broker.publish/3
```

It'd be great to instead get an error saying you need to add `publish :foo, ...` to `broker.ex`

**Comment by blatyo** [comment]
Thanks, it's addressed in this commit https://github.com/conduitframework/conduit/commit/960d83802a9692cf49ff59b12ab8e50ba9a9ca11
