### ISSUE TITLE
Generate docs for queues/exchanges/publish routes/subscribe routes

### ISSUE THREAD

**Issue by blatyo** [conduitframework/conduit#9]

**Comment by zblanco** [comment]
Just re-iterating the Slack conversation about this feature request a little while back so it's somewhere more appropriate. Please correct/clarify as needed.

- In the [`__before_compile__`](https://github.com/conduitframework/conduit/blob/master/lib/conduit/broker/dsl.ex#L229-L236) macro in `broker.ex` grab user specified module doc to append an auto-generated representation of the broker describing things like queues, exchanges, publish routes, subscribe routes, etc.
- To build the exchange and queue descriptions, add some kind of `doc` function to the [`Topology`](https://github.com/conduitframework/conduit/blob/master/lib/conduit/broker/topology.ex#L1) module to process the `topology` module attribute to glean and generate the doc.
- Like the `topology` attribute processing, do the same for [publishers](https://github.com/conduitframework/conduit/blob/master/lib/conduit/broker/incoming_scope.ex) and [subscribers](https://github.com/conduitframework/conduit/blob/master/lib/conduit/broker/outgoing_scope.ex).

@blatyo Did you have any more thoughts on delegating the doc generation to the adapter? Maybe an  [adapter](https://github.com/conduitframework/conduit/blob/master/lib/conduit/adapter.ex) callback(s) that `topology` and scope modules consume?

**Comment by blatyo** [comment]
That's the gist of it. As far as adapter specific, optional callbacks on the adapter for each would be good. If the callback is not defined, it should fall back to the generic one.
